# fly.toml app configuration file for techsolutions-blog-api

app = "techsolutions-blog-api"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DB_PORT = "5432"
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
