# Generated by Django 5.1.5 on 2025-02-02 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagens')),
                ('artigo', models.TextField(max_length=4000)),
                ('artigo_do_autor', models.TextField(blank=True, max_length=4000, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
